/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module decoder_16 (
    input [1:0] in,
    output reg [3:0] out
  );
  
  
  
  always @* begin
    
    case (in)
      1'h0: begin
        out = 4'h8;
      end
      1'h1: begin
        out = 4'h4;
      end
      2'h2: begin
        out = 4'h2;
      end
      2'h3: begin
        out = 4'h1;
      end
      default: begin
        out = 4'bxxxx;
      end
    endcase
  end
endmodule
