/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder8_1 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] s,
    output reg [7:0] xb
  );
  
  
  
  reg [7:0] xb2;
  
  integer i;
  
  always @* begin
    s = 1'h0;
    for (i = 1'h0; i < 8; i = i + 1) begin
      xb2[(i)*1+0-:1] = b[(i)*1+0-:1] ^ alufn[0+0-:1];
    end
    
    case (alufn[0+0-:1])
      1'h0: begin
        s = a + xb2;
      end
      1'h1: begin
        s = a - xb2;
      end
    endcase
    xb = xb2;
  end
endmodule
