/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare8_4 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg [7:0] cmp
  );
  
  
  
  reg lsb;
  
  always @* begin
    cmp = 1'h0;
    lsb = 1'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        lsb = z;
      end
      2'h2: begin
        lsb = n ^ v;
      end
      2'h3: begin
        lsb = z | (n ^ v);
      end
    endcase
    cmp = {7'h00, lsb};
  end
endmodule
