/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux_6 (
    input [7:0] s,
    input [7:0] boole,
    input [7:0] cmp,
    input [7:0] shift,
    input [5:0] alufn,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn[4+1-:2])
      2'h0: begin
        out = s;
      end
      2'h1: begin
        out = boole;
      end
      2'h2: begin
        out = shift;
      end
      2'h3: begin
        out = cmp;
      end
    endcase
  end
endmodule
