/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module helloworld_ROM_8 (
    input [3:0] address,
    output reg [7:0] letter
  );
  
  
  
  localparam TEXT = 160'h0d0a216162636465666768696a6b6c6d6e6f7071;
  
  always @* begin
    letter = TEXT[(address)*8+7-:8];
  end
endmodule
