/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module hangman_display_14 (
    input clk,
    input rst,
    input [2:0] wrong,
    output reg [7:0] outsel1,
    output reg [7:0] outsel2,
    output reg [63:0] outpic1,
    output reg [63:0] outpic2,
    output reg [2:0] ct
  );
  
  
  
  wire [3-1:0] M_ctr_value;
  counter_25 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  wire [8-1:0] M_decode_out;
  reg [3-1:0] M_decode_in;
  hangdecoder_26 decode (
    .in(M_decode_in),
    .out(M_decode_out)
  );
  
  always @* begin
    
    case (wrong)
      1'h1: begin
        outpic1 = 64'hfffdfdfdfdfdfd01;
        outpic2 = 64'hffffffffffffff00;
      end
      2'h2: begin
        outpic1 = 64'hff9d6d616d9dfd01;
        outpic2 = 64'hffffffffffffff00;
      end
      2'h3: begin
        outpic1 = 64'hff9d6d616d9dfd01;
        outpic2 = 64'hfffffff0ffffff00;
      end
      3'h4: begin
        outpic1 = 64'hff9d6d616d9dfd01;
        outpic2 = 64'hfffbfdf0fdfbff00;
      end
      3'h5: begin
        outpic1 = 64'hff9d6d616d9dfd01;
        outpic2 = 64'hffdbedf0eddbff00;
      end
      default: begin
        outpic1 = 64'hffffffffffffffff;
        outpic2 = 64'hffffffffffffffff;
      end
    endcase
    M_decode_in = M_ctr_value;
    outsel1 = M_decode_out;
    outsel2 = M_decode_out;
    ct = M_ctr_value;
  end
endmodule
