/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder8_3 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg xb7;
  
  reg [7:0] ss;
  
  always @* begin
    xb7 = 1'h0;
    ss = 1'h0;
    
    case (alufn[0+0-:1])
      1'h0: begin
        ss = a + b;
      end
      1'h1: begin
        ss = a - b;
      end
    endcase
    xb7 = b[7+0-:1] ^ alufn[0+0-:1];
    z = ~((|ss));
    v = (a[7+0-:1] & xb7 & ~ss[7+0-:1]) | (~a[7+0-:1] & ~xb7 & ss[7+0-:1]);
    n = ss[7+0-:1];
    s = ss;
  end
endmodule
