/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift8_6 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] shift
  );
  
  
  
  always @* begin
    shift = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        if (b[2+0-:1] == 1'h1) begin
          shift = a << 3'h4;
        end
        if (b[1+0-:1] == 1'h1) begin
          shift = a << 2'h2;
        end
        if (b[0+0-:1] == 1'h1) begin
          shift = a << 1'h1;
        end
      end
      2'h1: begin
        if (b[2+0-:1] == 1'h1) begin
          shift = a >> 3'h4;
        end
        if (b[1+0-:1] == 1'h1) begin
          shift = a >> 2'h2;
        end
        if (b[0+0-:1] == 1'h1) begin
          shift = a >> 1'h1;
        end
      end
      2'h3: begin
        if (b[2+0-:1] == 1'h1) begin
          shift = $signed(a) >>> 3'h4;
        end
        if (b[1+0-:1] == 1'h1) begin
          shift = $signed(a) >>> 2'h2;
        end
        if (b[0+0-:1] == 1'h1) begin
          shift = $signed(a) >>> 1'h1;
        end
      end
    endcase
  end
endmodule
