/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module zvn_2 (
    input [7:0] s,
    input [7:0] a,
    input [7:0] xb,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    z = ~((|s));
    v = (a[7+0-:1] & xb[7+0-:1] & ~s[7+0-:1]) | (~a[7+0-:1] | ~xb[7+0-:1] | s[7+0-:1]);
    n = s[7+0-:1];
  end
endmodule
